# mainブランチにpushされたとき、自動的に静的デプロイするワークフロー
name: 自動デプロイ

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/deploy-workflow

jobs:
  auto_deploy:
    name: GitHub Pagesに静的デプロイ
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pagesに静的デプロイ
        working-directory: ..
        run: yarn deploy
