# mainブランチにpushされたとき、自動的に静的デプロイするワークフロー
name: 自動デプロイ

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/deploy-workflow

jobs:
  auto_deploy:
    name: GitHub Pagesに静的デプロイ
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
      - name: GitHub Pagesに静的デプロイ
        run: |
          yarn install
          git config --global user.email "ttttt.fms5@gmail.com"
          git config --global user.name "tkawa15"
          yarn deploy
